config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  devise_for :users
  resources :users
  get 'accounts/import', to: 'accounts#import'
  get 'accounts/isack_waserman', to: 'accounts#isack_waserman'
  post 'accounts/import', to: 'accounts#import'

  resources :phones
  resources :accounts

  post 'callbacks/portOutValidationCallbackApi', to:'callbacks#portOutValidationCallbackApi'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :phones, :dependent => :destroy
  include ActiveModel::Serializers::Xml
end

app/controllers/accounts_controller.rb
require 'csv'
require 'pp'

class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])
    @phone = Phone.where("account_id = '#{params[:id]}'")
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import()
    @rows = []
    if params[:accounts]
      CSV.foreach(params[:accounts][:csv].tempfile, :headers =>  true) do |row|
          @account = Account.create({
                                   :pon => row[0],
                                   :pin => row[1],
                                   :account_number => row[2],
                                   :zip_code => row[3],
                                   :subscriber_name => row[4],
                                 })
      end
    end
  end

   def isack_waserman
	file_name = "/home/german.gimenez/port_out_validation_call_back_api/log/transactions.log"
	@log = File.open(file_name, "r")	
   end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:pon, :pin, :account_number, :zip_code, :subscriber_name)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pon, 'Phone Number' %>
    <%= form.text_field :pon, id: :account_pon %>
  </div>

  <div class="field">
    <%= form.label :pin %>
    <%= form.text_field :pin, id: :account_pin %>
  </div>

  <div class="field">
    <%= form.label :account_number, '4PSA Extn Number' %>
    <%= form.text_field :account_number, id: :account_account_number %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code, id: :account_zip_code %>
  </div>

  <div class="field">
    <%= form.label :subscriber_name %>
    <%= form.text_field :subscriber_name, id: :account_subscriber_name %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Phone', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/import.html.erb
<div class="row">
    <div class="col-lg-6">
        <h2>Import Accounts</h2>
<%= form_for :accounts do |f| %>
    <%= f.file_field :csv %>
    <%= f.submit %>
<% end %>
    </div>
    <% unless @rows.nil? %>
        <% @rows.each do |row|  %>
            <%= row[0] %>
        <% end %>
    <% end %>
</div>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Phone Number</th>
      <th>Pin</th>
      <th>4PSA Extn Number</th>
      <th>Zip code</th>
      <th>Subscriber name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.pon %></td>
        <td><%= account.pin %></td>
        <td><%= account.account_number %></td>
        <td><%= account.zip_code %></td>
        <td><%= account.subscriber_name %></td>
        
        <td><%= link_to 'Add Phone', new_phone_path %></td>

        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/isack_waserman.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<% @log.each_line { |line| %>
	<p><%= line %></p>
<% } %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone Number:</strong>
  <%= @account.pon %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @account.pin %>
</p>

<p>
  <strong>4PSA Extn Number:</strong>
  <%= @account.account_number %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @account.zip_code %>
</p>

<p>
  <strong>Subscriber name:</strong>
  <%= @account.subscriber_name %>
</p>

<p>
  <% @phone.each do |p| %>
    <p> <strong>Phones:</strong> <%= p.phone_number %></p>
  <% end %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>